---
output: github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "figs/",
  fig.height = 3,
  fig.width = 4,
  fig.align = "center"
)
```

[\@drsimonj](https://twitter.com/drsimonj) here to share a super simple method for creating beautiful ordered bar plots like these:

```{r init-example, message = FALSE, echo = F}
library(dplyr)
library(ggplot2)

ourworldindata::child_mortality %>% 
  tidyr::drop_na() %>%
  count(continent) %>% 
  mutate(continent = reorder(continent, n)) %>% 
  ggplot(aes(x = continent, y = n, fill = n)) +
    geom_col(show.legend = FALSE) +
    theme_minimal()

ourworldindata::child_mortality %>% 
  tidyr::drop_na() %>%
  count(continent) %>% 
  mutate(continent = reorder(continent, n)) %>% 
  ggplot(aes(x = continent, y = n, fill = n)) +
    geom_col(show.legend = FALSE) +
    theme_minimal()

```



## Sign off

Thanks for reading and I hope this was useful for you.

For updates of recent blog posts, follow [\@drsimonj](https://twitter.com/drsimonj) on Twitter, or email me at <drsimonjackson@gmail.com> to get in touch.

If you'd like the code that produced this blog, check out the [blogR GitHub repository](https://github.com/drsimonj/blogR).